[build]
  command = "npm install && npm run build"
  publish = "client/.next"

[[redirects]]
  from = "/*"
  to = "/index.html"
  status = 200

[build.environment]
  NEXT_PUBLIC_API_URL = "https://your-server-url.herokuapp.com" # We'll update this later
  NODE_VERSION = "18" 